#!/bin/sh

get_python()
{
    if [ -f /usr/bin/python2.4.i386 ]; then
        eval "$1=/usr/bin/python2.4.i386"
    else
        eval "$1=python"
    fi
}

abspath()
{
    case "$1" in
        
    /*)
        eval "$2=$1"
        ;;

    *)
        eval $2=`pwd`/`basename $1`
        ;;
    esac
}

prepend_path_element()
{
    echo $3 | grep -q $1
    if [ $? = 1 ]; then
        eval $2=$1:$3
    fi
}

abspath $0 fullpath
prepend_path_element /users/geoff/pygtk_test/lib/ LD_LIBRARY_PATH $LD_LIBRARY_PATH
prepend_path_element /users/geoff/pygtk_test/lib/python2.4/site-packages/gtk-2.0:/users/geoff/pygtk_test/lib/python2.3/site-packages PYTHONPATH $PYTHONPATH
export LD_LIBRARY_PATH PYTHONPATH
export GDK_PIXBUF_MODULE_FILE=/users/geoff/pygtk_test/lib/gtk-2.0/gdk-pixbuf.loaders
export PANGO_RC_FILE=/users/geoff/pygtk_test/pango/pangorc
export GTK2_RC_FILES=/users/geoff/pygtk_test/lib/gtk-2.0
export TEXTTEST_SLAVE_CMD=$fullpath
get_python python
exec $python ${fullpath}.py "$@"
